Code :
name: model-supervisÃ© RL
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container : docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.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 }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python 01_prod_regression_ci__tutorial.py
          # Write your CML report
          echo "## Metriques:" >> report.md
          cat metrics.txt >> report.md
